pet:
	g++ petunin.cpp `Magick++-config --cppflags --cxxflags --ldflags --libs` -o pet

dumb:
	g++ petunin_dumb.cpp `Magick++-config --cppflags --cxxflags --ldflags --libs` -o dumb

marg:
	g++ marginal.cpp `Magick++-config --cppflags --cxxflags --ldflags --libs` -o marg

clean:
	rm pet marg dumb
