box:
	g++ -std=c++11 -DDEBUG -DBITMAP fractal_dim.cpp EasyBMP/EasyBMP.cpp -o box

freq:
	g++ -std=c++11 -DDEBUG frequency_analysis.cpp EasyBMP/EasyBMP.cpp -o freq -lfftw3

test_fft:
	g++ -std=c++11 EasyBMP/EasyBMP.cpp -o test_fft -lfftw3
